### ISSUE TITLE
use pendulum module for datetime

### ISSUE THREAD

**Issue by franTarkenton** [ironwoodcall/TagTracker#16]
IMO a big miss for python is how it implements date time type operations... datetime objects, time objects, time tuples, unix epoch (seconds from some date in 1970!!!), then add in timezones and pytz module... It feels messy.  Consider using this module:

https://pendulum.eustace.io/

its the closest thing to a clean datetime interface.

**Comment by tevpg** [comment]
1. Times are currently stored throughout as 5-chr strings ISO8601 format (HH:MM). Would definitely be nice to use a time object of some kind.  I had considered using int "minutes since midnight" as a straightforward replacement
2. Product owner (@ironwoodcall ) identifies as a goal to avoid non-core dependencies, so need to balance dependency against an improved implementation

**Comment by tevpg** [comment]
I don’t see this happening until TagTracker becomes multi-day or has too cover shifts that extend over midnight
