### ISSUE TITLE
tracker2db et al cleanup and tweak

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#251]
- [x] Change database interaction statements to UPDATE the `day` table instead of deleting and inserting rows; other sources of data (eg weather, leftover counts sometimes) now exist and tracker2db needs not to own this table
- [x]  replace get_date() in tracker2db.py with date_str('today')
- [x] #248 
- [x] constraints for counts of various lengths of stays should be allowed to be zero
- [x] tracker2db: check for and reject loudly a visit that starts after recorded closing time -- this is always some kind of problem we should know about
- [x] Replace general SQL use functions with those in `tt_dbutil` (duplicate and more robust functionality):
  - [x] `create_connection()` -> `tt_dbutil.db_connect()`
  -  ~`sql_do(<insert into ...>)` - > `tt_dbutil.db_update(<update ...>)`~ slightly different behaviour than wanted
  - [x] `ut.get_date()` (deprecated) -> `ut.date_str("today")`
  -  ~weird oneoff queries -> `tt_dbutil.db2day`, `-.db_latest` and derivatives~ seems extra for now
- [x] #211

**Comment by tevpg** [comment]
Awesome!
- be aware that dbutil.db2day() will create best-guess tag lists (regular,oversize).  If this is not desired for your use case then add a switch to db2day()
- consider testing for a tag whose bike is checked-in later than recorded closing time -- this was a problem for one day when there was a tag in after recorded closing time then abandoned -- tracker2db tried to do calculate a negative duration...  Admittedly this is a super edge case (and the recorded closing time was incorrect) but know that the possibility exists.
- UPDATE instead of INSERT for DAY definitely; much less important for VISIT, which I am happy to consider 100% determined from the incoming datafile.

**Comment by ironwoodcall** [comment]
1. Good to know, I'll have a look at how that's decided before implementing it
2. Fun, fun. I'll add a check for this and have tracker2db and/or the database complain loudly if this comes up again
3. Ok, `visit` will stay owned by tracker2db for now since it's simpler that way and not necessary to change
