### ISSUE TITLE
canonical_tag definition regex

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#30]
Tags may not necessarily have just one letter as a colour abbreviation. The abbreviation the tag spreadsheet uses for "purple" is "pu" to distinguish it from "p" for "pink".

**Comment by tevpg** [comment]
OMG.  HUGE eye-roll.  But ok.  

I have given some thought to colours btw.  In graphics work, B=blue, K=black.  In electronics (if I remember right), blue is BU, black is BK.  If it were up to me, I'd simply say that all colours are single-letter and that "purple" is actually Lavender (L) or Violet (V).

There is a practice of allowing people to shorten commands arbitrarily, as long as they remain unambiguous.  (In this scenario, you could exit the program with exit, exit, or ex -- but not 'e' because that also matches 'edit'.  Would capital bike consider applying this logic to colours?  The obvious failing is around black and blue, which would each require 3 characters.
So if it were up to me we would make all the tags have single-character abbreviations (we could even write them on the corners of the tags with sharpie).  And yes, a person would have to actually TRAIN THE STAFF, but realy, this job as a much lower-than-normal amount of training, so I don't think that would be asking too much.

FIRST thing I'd do is swap out the black tags (which by convention should be "K") for blue tags, which could quite reasonably be B.

**Comment by tevpg** [comment]
function parse_tag() will do intelligent parsing of tags into its constituent bits (yes even 2-letter colours) and check for the usability of the tag.  Suggest using this throughout.  See [pull request 38](https://github.com/ironwoodcall/TagTracker/pull/38)

**Comment by tevpg** [comment]
Oh, and I can't help but notice that the data collection spreadsheet suggests that purple is represented by the single letter 'U'
